const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={products:[],query:'',category:'All',brand:'',model:'',year:'',engine:'',sort:'featured',page:1,pageSize:8,cart:JSON.parse(localStorage.getItem('volktec-cart')||'{}')};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function init(){try{const res=await fetch('data/products.json');if(!res.ok)throw new Error();state.products=(await res.json()).map((p,i)=>({sku:`VT-${String(i+1).padStart(5,'0')}`,manufacturerNumber:p.partNumber,quantity:Math.max(1,(i%7)+1),condition:'New',description:`Quality ${p.brand} replacement part for the Volkswagen applications shown. Verify the OE number and vehicle details before ordering.`,position:'See application',shipping:'Fast U.S. shipping options will be calculated at checkout.',images:[],ebayItemNumber:'',...p}));renderCategories();renderBrowse();setupFitment();renderModels();applyFilters();renderCart();const hash=location.hash.match(/^#product\/(.+)$/);if(hash)openProduct(hash[1])}catch(e){$('[data-result-summary]').textContent='Catalog could not be loaded. Please refresh or contact us.'}bindEvents();$('[data-year]').textContent=new Date().getFullYear()}
function bindEvents(){$$('[data-search-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();state.query=$('#hero-query').value.trim();$('[data-catalog-search]').value=state.query;state.page=1;applyFilters();$('#catalog').scrollIntoView()}));$('[data-catalog-search]').addEventListener('input',e=>{state.query=e.target.value.trim();state.page=1;applyFilters()});$('[data-sort]').addEventListener('change',e=>{state.sort=e.target.value;applyFilters()});$('[data-clear-filters]').addEventListener('click',clearFilters);$('[data-open-cart]').addEventListener('click',openCart);$$('[data-close-cart]').forEach(b=>b.addEventListener('click',closeCart));$('[data-cart-backdrop]').addEventListener('click',closeCart);$$('[data-close-product]').forEach(b=>b.addEventListener('click',closeProduct));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeProduct()}});$('[data-checkout]').addEventListener('click',checkout)}
function renderCategories(){const counts={};state.products.forEach(p=>counts[p.category]=(counts[p.category]||0)+1);const cats=['All',...Object.keys(counts)];const icons={All:'511',Engine:'ENG',Brakes:'BRK',Electrical:'12V',Suspension:'SUS',Drivetrain:'DRV',Exterior:'EXT'};$('[data-categories]').innerHTML=cats.slice(0,6).map(c=>`<button class="category-card ${c==='All'?'active':''}" data-category="${escapeHtml(c)}"><span class="category-icon">${icons[c]||'VW'}</span><strong>${escapeHtml(c==='All'?'All parts':c)}</strong><small>${c==='All'?'Full catalog ready':`${counts[c]} sample item${counts[c]===1?'':'s'}`}</small></button>`).join('');$$('[data-category]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;state.page=1;applyFilters();$('#catalog').scrollIntoView()}))}
function renderBrowse(){const categories=['Engine','Fuel & Injection','Electrical & Ignition','Alternators & Starters','Brakes','Suspension & Steering','Transmission & Clutch','Cooling','Exhaust','Interior','Exterior','Lights & Lenses','Hardware & Miscellaneous'];const brands=[...new Set(state.products.map(p=>p.brand))].sort();$('[data-all-categories]').innerHTML=categories.map(c=>`<button class="chip" data-chip-category="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('');$('[data-brands]').innerHTML=brands.map(b=>`<button class="chip" data-brand="${escapeHtml(b)}">${escapeHtml(b)}</button>`).join('');$$('[data-chip-category]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.chipCategory;state.page=1;applyFilters();$('#catalog').scrollIntoView()}));$$('[data-brand]').forEach(b=>b.addEventListener('click',()=>{state.brand=b.dataset.brand;state.page=1;applyFilters();$('#catalog').scrollIntoView()}))}
function setupFitment(){const yearSelect=$('[name=year]'),modelSelect=$('[name=model]'),engineSelect=$('[name=engine]');const years=[...new Set(state.products.flatMap(p=>p.fitment.flatMap(f=>range(f.from,f.to))))].sort((a,b)=>b-a);yearSelect.innerHTML='<option value="">Any year</option>'+years.map(y=>`<option>${y}</option>`).join('');yearSelect.addEventListener('change',()=>{const y=+yearSelect.value;const models=[...new Set(state.products.flatMap(p=>p.fitment.filter(f=>!y||(y>=f.from&&y<=f.to)).map(f=>f.model)))].sort();modelSelect.disabled=!y;modelSelect.innerHTML=y?'<option value="">All models</option>'+models.map(m=>`<option>${escapeHtml(m)}</option>`).join(''):'<option value="">Select a year first</option>';engineSelect.disabled=true;engineSelect.innerHTML='<option value="">Select a model first</option>'});modelSelect.addEventListener('change',()=>{const model=modelSelect.value,y=+yearSelect.value;const engines=[...new Set(state.products.filter(p=>p.fitment.some(f=>f.model===model&&(!y||(y>=f.from&&y<=f.to)))).flatMap(p=>p.engine))].sort();engineSelect.disabled=!model;engineSelect.innerHTML=model?'<option value="">All engines</option>'+engines.map(e=>`<option>${escapeHtml(e)}</option>`).join(''):'<option value="">Select a model first</option>'});$('[data-fitment-form]').addEventListener('submit',e=>{e.preventDefault();state.model=modelSelect.value;state.year=yearSelect.value;state.engine=engineSelect.value;state.page=1;applyFilters();$('#catalog').scrollIntoView()})}
function renderModels(){const models=[...new Set(state.products.flatMap(p=>p.fitment.map(f=>f.model)))];$('[data-models]').innerHTML=models.slice(0,6).map(m=>`<button class="model-card" data-model-card="${escapeHtml(m)}"><strong>${escapeHtml(m)}</strong><span>Shop compatible parts →</span></button>`).join('');$$('[data-model-card]').forEach(b=>b.addEventListener('click',()=>{state.model=b.dataset.modelCard;state.page=1;applyFilters();$('#catalog').scrollIntoView()}))}
function range(a,b){const out=[];for(let y=a;y<=b;y++)out.push(y);return out}
function filtered(){const q=state.query.toLowerCase().replace(/[\s-]/g,'');let items=state.products.filter(p=>{const hay=[p.name,p.sku,p.partNumber,p.manufacturerNumber,...p.alternateNumbers,p.brand,p.category,p.description].join(' ').toLowerCase().replace(/[\s-]/g,'');const fit=p.fitment.some(f=>(!state.model||f.model===state.model)&&(!state.year||(+state.year>=f.from&&+state.year<=f.to)));return (!q||hay.includes(q))&&(state.category==='All'||p.category===state.category)&&(!state.brand||p.brand===state.brand)&&(!state.engine||p.engine.includes(state.engine))&&fit});if(state.sort==='price-asc')items.sort((a,b)=>a.price-b.price);if(state.sort==='price-desc')items.sort((a,b)=>b.price-a.price);if(state.sort==='name')items.sort((a,b)=>a.name.localeCompare(b.name));return items}
function applyFilters(){const items=filtered(),pages=Math.max(1,Math.ceil(items.length/state.pageSize));state.page=Math.min(state.page,pages);const shown=items.slice((state.page-1)*state.pageSize,state.page*state.pageSize);$('[data-result-summary]').textContent=`${items.length} ${items.length===1?'part':'parts'} shown from the current sample catalog`;$('.product-grid').innerHTML=shown.map(card).join('');$('[data-empty]').hidden=items.length>0;renderPagination(pages);$$('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===state.category));$$('[data-chip-category]').forEach(b=>b.classList.toggle('active',b.dataset.chipCategory===state.category));$$('[data-brand]').forEach(b=>b.classList.toggle('active',b.dataset.brand===state.brand));renderFilter();$$('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(b.dataset.add)));$$('[data-product]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.product)))}
function card(p){const fit=p.fitment.slice(0,2).map(f=>`${f.model} ${f.from}–${f.to}`).join(' · ');return `<article class="product-card"><button class="product-title-button" data-product="${p.id}" aria-label="View ${escapeHtml(p.name)}"><div class="product-media"><span class="product-badge">${escapeHtml(p.brand)}</span><div class="part-silhouette">${escapeHtml(p.category)}<br>PART</div></div></button><div class="product-body"><span class="part-number">VW/OE # ${escapeHtml(p.partNumber)}</span><button class="product-title-button" data-product="${p.id}"><h3>${escapeHtml(p.name)}</h3></button><p class="fitment">Fits ${escapeHtml(fit)}</p><p class="stock">✓ ${p.quantity} in stock</p><button class="detail-link" data-product="${p.id}">View details & fitment</button><div class="product-buy"><strong class="price">${money(p.price)}</strong><button class="add-button" type="button" data-add="${p.id}">Add to cart</button></div></div></article>`}
function renderPagination(pages){$('[data-pagination]').innerHTML=pages<=1?'':Array.from({length:pages},(_,i)=>`<button type="button" class="${state.page===i+1?'active':''}" data-page="${i+1}" aria-label="Page ${i+1}">${i+1}</button>`).join('');$$('[data-page]').forEach(b=>b.addEventListener('click',()=>{state.page=+b.dataset.page;applyFilters();$('#catalog').scrollIntoView()}))}
function renderFilter(){const bits=[];if(state.query)bits.push(`Search: “${escapeHtml(state.query)}”`);if(state.category!=='All')bits.push(state.category);if(state.brand)bits.push(state.brand);if(state.model)bits.push(`${state.model}${state.year?' '+state.year:''}${state.engine?' '+state.engine:''}`);const el=$('[data-active-filter]');el.hidden=!bits.length;el.innerHTML=bits.length?`${bits.join(' &nbsp;·&nbsp; ')} <button type="button" data-inline-clear aria-label="Clear filters">×</button>`:'';if(bits.length)$('[data-inline-clear]').addEventListener('click',clearFilters)}
function clearFilters(){Object.assign(state,{query:'',category:'All',brand:'',model:'',year:'',engine:'',page:1});$('[data-catalog-search]').value='';$('#hero-query').value='';$('[name=year]').value='';$('[name=year]').dispatchEvent(new Event('change'));applyFilters()}
function openProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;const fit=p.fitment.map(f=>`${f.model} ${f.from}–${f.to}`).join(', ');$('[data-product-detail]').innerHTML=`<p class="eyebrow">${escapeHtml(p.brand)} · ${escapeHtml(p.condition)}</p><h2 id="product-detail-title">${escapeHtml(p.name)}</h2><div class="detail-price">${money(p.price)}</div><p class="detail-stock">✓ ${p.quantity} available</p><p>${escapeHtml(p.description)}</p><div class="detail-buy"><input type="number" value="1" min="1" max="${p.quantity}" aria-label="Quantity"><button data-detail-add="${p.id}">Add to cart</button></div><div class="spec-table"><div class="spec-row"><strong>Volktronix SKU</strong><span>${escapeHtml(p.sku)}</span></div><div class="spec-row"><strong>VW/OE number</strong><span>${escapeHtml(p.partNumber)}</span></div><div class="spec-row"><strong>Manufacturer #</strong><span>${escapeHtml(p.manufacturerNumber)}</span></div><div class="spec-row"><strong>Interchange</strong><span>${escapeHtml(p.alternateNumbers.join(', ')||'—')}</span></div><div class="spec-row"><strong>Fitment</strong><span>${escapeHtml(fit)}</span></div><div class="spec-row"><strong>Engine</strong><span>${escapeHtml(p.engine.join(', ')||'See application')}</span></div><div class="spec-row"><strong>Position</strong><span>${escapeHtml(p.position)}</span></div></div><div class="detail-sections"><details open><summary>Description & specifications</summary><p>${escapeHtml(p.notes)}</p></details><details><summary>Shipping</summary><p>${escapeHtml(p.shipping)}</p></details><details><summary>Returns</summary><p>Returns policy will be finalized before launch. Contact us before returning an item.</p></details><details><summary>Related parts</summary><p>Related-product recommendations will be generated from category and fitment data.</p></details></div>`;$('[data-detail-add]').addEventListener('click',()=>{const qty=Math.max(1,Math.min(p.quantity,+$('.detail-buy input').value||1));state.cart[p.id]=(state.cart[p.id]||0)+qty;saveCart();renderCart();closeProduct();openCart()});$('[data-product-modal]').hidden=false;document.body.style.overflow='hidden';$('.detail-close').focus();history.replaceState(null,'',`#product/${p.id}`)}
function closeProduct(){$('[data-product-modal]').hidden=true;document.body.style.overflow='';if(location.hash.startsWith('#product/'))history.replaceState(null,'','#catalog')}
function addToCart(id){state.cart[id]=(state.cart[id]||0)+1;saveCart();renderCart();showToast('Added to your cart')}
function saveCart(){localStorage.setItem('volktec-cart',JSON.stringify(state.cart))}
function renderCart(){const lines=Object.entries(state.cart).map(([id,qty])=>({p:state.products.find(x=>x.id===id),qty})).filter(x=>x.p);const count=lines.reduce((s,x)=>s+x.qty,0),total=lines.reduce((s,x)=>s+x.p.price*x.qty,0);$('[data-cart-count]').textContent=count;$('[data-cart-empty]').hidden=lines.length>0;$('[data-cart-footer]').hidden=!lines.length;$('[data-cart-subtotal]').textContent=money(total);$('[data-cart-items]').innerHTML=lines.map(({p,qty})=>`<div class="cart-line"><div class="cart-thumb"></div><div><h3>${escapeHtml(p.name)}</h3><small># ${escapeHtml(p.partNumber)} · ${money(p.price)}</small><div class="quantity"><button data-qty="${p.id}" data-delta="-1" aria-label="Decrease quantity">−</button><span>${qty}</span><button data-qty="${p.id}" data-delta="1" aria-label="Increase quantity">+</button></div></div><button class="remove" data-remove="${p.id}">Remove</button></div>`).join('');$$('[data-qty]').forEach(b=>b.addEventListener('click',()=>changeQty(b.dataset.qty,+b.dataset.delta)));$$('[data-remove]').forEach(b=>b.addEventListener('click',()=>changeQty(b.dataset.remove,-999)))}
function changeQty(id,delta){state.cart[id]=Math.max(0,(state.cart[id]||0)+delta);if(!state.cart[id])delete state.cart[id];saveCart();renderCart()}
function openCart(){$('[data-cart-backdrop]').hidden=false;$('#cart-drawer').classList.add('open');$('#cart-drawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('[data-close-cart]').focus()}
function closeCart(){$('[data-cart-backdrop]').hidden=true;$('#cart-drawer').classList.remove('open');$('#cart-drawer').setAttribute('aria-hidden','true');document.body.style.overflow=''}
async function checkout(){const note=$('[data-checkout-note]');note.textContent='Checkout connection is ready for Stripe setup. No payment has been taken.'}
let toastTimer;function showToast(msg){const el=$('[data-toast]');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
init();

